### ISSUE TITLE
Can support FlagReranker for BAAI/bge-reranker-v2-m3

### ISSUE THREAD

**Issue by edisonzf2020** [AnswerDotAI/rerankers#12]

**Comment by bclavie** [comment]
On it! Will be shipped soon :)

**Comment by bclavie** [comment]
Whoops sorry I spoke a bit too fast!

Bge-reranker-v2-m3 is fully supported in huggingface, so as a normal `crossencoder`. I'm trying to keep dependencies fairly lightweights, so is there any reason you'd require the FlagEmbedding equivalent instead @edisonzf2020 ?
