### ISSUE TITLE
Support for huggingface Text Embeddings Inference Server

### ISSUE THREAD

**Issue by Johnno1011** [AnswerDotAI/rerankers#2]
HF TEI supports some reranking models such as BAAI and jina - would it be possible to include the TEI API as a supported usecase for rerankers?
Thanks :)

**Comment by bclavie** [comment]
Hey, this is a great shout, thank you! I'll try and have it included in the next release, and leave this open in case someone wants to contribute it before I do :)

**Comment by srisudarsan** [comment]
Hello @bclavie , can you please have a look on the PR and let know your comments if any ?
