### ISSUE TITLE
Pinecone Rerank API Support

### ISSUE THREAD

**Issue by gdj0nes** [AnswerDotAI/rerankers#31]
We (Pinecone) would be interested in contributing to support for rerankers hosted in our API. Would you be open to this?

**Comment by bclavie** [comment]
Hey. We're more than happy to add just about any (serious) method to the library, so this would be a welcome PR, as long as it respects the core design principle (being an optional dependency, not affecting other methods, etc...)!

**Comment by bclavie** [comment]
Hey @gdj0nes, any updates on this? Closing the issue as stale for now, but happy to help you guys integrate this if you're still looking to!

**Comment by gdj0nes** [comment]
Sounds good @bclavie. Trying to find bandwidth on our end!
