### ISSUE TITLE
❗️ `FlashRankRanker` ranking is incorrect – it returns the documents in input order

### ISSUE THREAD

**Issue by lsorber** [AnswerDotAI/rerankers#39]
The ranking produced by `FlashRankRanker` is incorrect. It returns the documents in input order.

This statement in `flashrank_ranker.py`[^1]
```python
        ranked_results = [
            Result(
                document=docs[idx],  # Returns documents in input order.
                score=result["score"],
                rank=idx + 1,
            )
            for idx, result in enumerate(flashrank_results)
        ]
```
should be:
```python
        ranked_results = [
            Result(
                document=docs[result["id"]],  # Returns reranked documents.
                score=result["score"],
                rank=idx + 1,
            )
            for idx, result in enumerate(flashrank_results)
        ]
```

[^1]: https://github.com/AnswerDotAI/rerankers/blob/c5b2c19e7a84fc4c4dd3f31dea934297ce4b7bb1/rerankers/models/flashrank_ranker.py#L48

**Comment by bclavie** [comment]
Fixed in https://github.com/AnswerDotAI/rerankers/pull/46, coming up in today's release. Do feel free to submit a PR if you'd like in the future -- we very much welcome these contributons!
