### ISSUE TITLE
lightweight rerankers

### ISSUE THREAD

**Issue by bolbolamir** [AnswerDotAI/rerankers#40]
hello, I sincerely apologize for asking this question in issues, I wanted to know what are some of the really lightweight < 100Mb rankers if you happen to know? and also are there any lexical rankers that only care about exact and fuzzy matches?

**Comment by bclavie** [comment]
>  some of the really lightweight < 100Mb rankers if you happen to know?

You've got a couple decent options in this area, but you'll need to use half-precision:
- our own [answerai-colbert-small-v1](https://huggingface.co/answerdotai/answerai-colbert-small-v1), a ColBERT model, is ~67MB when used in 16-bit precision
- Jina's [jina-reranker-v1-turbo-en](https://huggingface.co/jinaai/jina-reranker-v1-turbo-en) is 75MB in BF16

> and also are there any lexical rankers that only care about exact and fuzzy matches

No general-purpose, widely-used one as far as I'm aware. Though it's relatively easy to build, depending on which lexical distance you care about!
