### ISSUE TITLE
GPT-4o from RankLLM does not work for TREC DL19 and 20 query

### ISSUE THREAD

**Issue by Mandeep-Rathee** [AnswerDotAI/rerankers#41]
Hey,
thanks for providing the wonderful library.

I am using GPT-4o model from RankLLM as a Ranker. I use BM25 as the initial retriever (take top 100 results). My code breaks for only one query from each TREC DL19  and DL20. For TREC DL19, the query ID is "131843" and the query is
 
`definition of a sigmet`

For DL20, the query id is "768208" and the query is

`what is mamey`

The error seems to be from the incorporated [rank_llm](https://github.com/castorini/rank_llm/blob/main/src/rank_llm/rerank/listwise/rank_gpt.py#L162C1-L179C56) library   

```python
    def run_llm(
        self,
        prompt: Union[str, List[Dict[str, str]]],
        current_window_size: Optional[int] = None,
    ) -> Tuple[str, int]:
        model_key = "model"
        response = self._call_completion(
            messages=prompt,
            temperature=0,
            completion_mode=SafeOpenai.CompletionMode.CHAT,
            return_text=True,
            **{model_key: self._model},
        )
       
        try:
            encoding = tiktoken.get_encoding(self._model)
        except:
            encoding = tiktoken.get_encoding("cl100k_base")
        return response, len(encoding.encode(response))
``` 

I am getting the following error:

```python
lib/python3.11/site-packages/tiktoken/core.py", line 111, in encode                                                                        
    raise TypeError(f"Expected 'text' to be a string, but got {type(text)}")                                                                                                  
TypeError: Expected 'text' to be a string, but got <class 'NoneType'> 
```  
                                                                                         `
The response is None
```python
print(response)
>> None
```

This is the output from [completion](https://github.com/castorini/rank_llm/blob/main/src/rank_llm/rerank/listwise/rank_gpt.py#L132) 

```python
ChatCompletion(id=None, choices=[Choice(finish_reason='stop', index=None, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant'
, function_call=None, tool_calls=None))], created=1728425889.0, model='gpt-4o', object='chat.completion', service_tier=None, system_fingerprint='fp_67802d9a6d', usage=Complet
ionUsage(completion_tokens=None, prompt_tokens=1462, total_tokens=1462), duration={'total': 312499305}, estimated_cost={'prompt': 0.00731, 'total': 0.00731})
``` 

Is there any way to fix the issue? 

thanks

**Comment by bclavie** [comment]
Thank you for flagging this. It seems like the underlying rankllm implementation indeed doesn't have error catching mechanisms for situations where the distant provider simply refuses to respond to a given prompt, for whatever reason. Potentially, we could add a second implementation of listwise LLM reranking which'd circumvent this issue (if possible).

I think our policy here is to respect the original implementations as much as possible, and failing loudly is potentially a more intuitive behaviour than just silently catching the error. I might add a try/except that will still raise an error, with a more useful error description.
