### ISSUE TITLE
Add FlashRank(cross-encoder/ms-marco-TinyBERT-L-2 on cpu)

### ISSUE THREAD

**Issue by tarasglek** [AnswerDotAI/rerankers#8]
I love your collection of rerankers, really interesting to see all of them side-by-side

There is one more fun one that you could add:
https://github.com/PrithivirajDamodaran/FlashRank is a cool lib which boasts crazy good cpu perf

**Comment by bclavie** [comment]
Very good shout, I'll see to it this week, thank you!

**Comment by bclavie** [comment]
Live now https://github.com/AnswerDotAI/rerankers/pull/10
